language: ruby
cache:
  bundler: true
  directories:
    - vendor/bundle
    - .sass-cache
install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - mkdir -p bin tmp/kindlegen
  - curl http://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz > tmp/kindlegen.tar.gz
  - tar zxvf tmp/kindlegen.tar.gz -C tmp/kindlegen
  - mv tmp/kindlegen/kindlegen bin/
before_script:
  - echo $TRAVIS_BUILD_NUMBER > _includes/travis_build_number.txt
script:
  - bundle exec rake build
after_success:
  - bin/deploy.sh
branches:
  except:
  - gh-pages
git:
  depth: 6
rvm:
  - 2.1.2
deploy:
  provider: releases
  api_key:
    secure: sw0+kTFWQOj0cvSUotCI2hU42cTCzObTMaJ2LrdLRdflzcj1a1Kci6rpCQSbgwzOHx+RfeDklXsxIg8hyfhd4CMYUNTUNindPSUB2r3TcfLkmWyP6hJQW8SEBtpqezfxwYs80gDfXk4akoRS8sLxotZcD6LZpyz4ht57ORV/iPyy3K63WARWxFgRb/fjkSUbN1UunLn8ykwhPWzee+1t+abE+d0zr/8lsJ3N3rx35Z+KzBq8PTZ7rycOCDfZsJbW+79HQQFjOcPjfDj0tChrSREmRuHHyQRqOSYFmZ/ezXQ48W9WOK/KrSa63aGJtk7yRjYL55+7JfD3r8yKC4JojHpz8imi0qwnzjCKeQphyMNLQyMDcJoNOB+Fw/3rrQk9v/JEl1gZbN4Ve5JkzPHja61Pb2LqIm9egJB74maVkhPgPJPfQSs3doIDx1IKaJfMuYct2m9TMyf8DY5ddIRdDd3fWMhzPSNBXur+RsBQUoiS5FQeKi1JWps0kNSIv1MTL1+5opM9eYj5rtUi9gp6tNY2XsLQfED+mQHFQz8d6XIz3CFtTbAb8DLc2WG98d20xMcS54NZ6w33ywtcaHhFg6gi+wmrzOg/yar6nm80QqkmrBgyKhfSeudfxW6JlaF8KtDQrXEfA8pNG5HayuePU6PhgB2NolVXGT3If1drQcA=
  file: _output/gotdict.mobi
  on:
    tags: true
    repo: wjdp/gotdict
    branch: master
env:
  global:
    secure: bqcgrvXw/ynOkS8HW5vCuGug5zFiYPyOYKyYN6F/Nndk9g9qMP9oBr0D6ssZgVL9GcKv+96p8x9bSwrCArPU1/ZUZNHPyQ3jchTfEkVrG4mifCFTC3ekDj1cKv5Et2thUs7JENSf8rmbVsxw5ckVKtmS4PHeKEh9CVYu6RnEt2aoWAbi2RUaI4YJoYwZydgR9LAqrgdP2snAC4K4eQnzINguwY7DdEi93Fi1Av+NyvPzrn/UCdk/5R8PNJcodryo+kBNzIAi8/sX1XQiMYqHlH3qetVeQw89odKFyVezcxLkejV/Et/xEqDvuB5Ghq1Vrn7LJIw1fsZZ3kt1ODWtlAITs2ZRjNmuxlxf4VD56Q3Eyr8SUKfrWHWXAqKgu3gTmKT05yPMXBBPucCHDkZtf7iNkX4SNSzOre69j2rZrJWdQhEbmnnd5Nq0OaHeNf/yFoC2KFF09re7Hu9rD/8vTS6TA3g0aAsv79EsaMzx7K+BERCIxQO+etXoC7hqtodflUNFO0iVfMLufsYquvZcV96WXChf9oUoMlzEaA2XrO7b7tMi3Nds5YFj7+Ct1iAakMRg7STqe7YAvk+8iBro3jGIW6Adyu9kbQpigLo1mDiIm/QgWlan5OO15gS7rKhMr4vIQ8ucehzS0qOadIqvSEgC95nToTAc5dz9wwjIWwY=
