language: ruby
cache:
  bundler: true
  directories:
    - vendor/bundle
    - .sass-cache
install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - mkdir -p bin tmp/kindlegen
  - curl http://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz > tmp/kindlegen.tar.gz
  - tar zxvf tmp/kindlegen.tar.gz -C tmp/kindlegen
  - mv tmp/kindlegen/kindlegen bin/
before_script:
  - echo $TRAVIS_BUILD_NUMBER > _includes/travis_build_number.txt
script:
  - bundle exec rake build
after_success:
  - bin/deploy.sh
branches:
  except:
  - gh-pages
git:
  depth: 6
rvm:
  - 2.1.2
deploy:
  provider: releases
  api_key:
    secure: b5qYl10xNFZ689L6PVzyi0zw9zMK6hV+boB9tS+XLJ6+e4X9DNr4cUdfE8mTeYcuBmZTZZn8biYhy9L0dzkQgfubqFIPS15zO7RaXZDoMEf9jRnKEbtFE90NJIqYbCwwLlFDAsevul2EeVQFsk8Mgp3b96QrxNQaDdU/bJu/dzftgoGq3F03/coXPj42uOArRt0YA5eEpIQVChBEZRy03iYlwCu5BaI7WKEcs/PDvwlOm+jf3gIZuC7l/wi6e3Ixnh7eXX/FfF4WJCIVZC5eGhCfkOvYbf6u8tk9HrW296r4JjgvBR5VjtrRA8QXRGzjA7Q+A5hkj7/WCUwUIhzYOHnb5/73sNUHzo94k0P+uFBeJO0U1STPChdWNSVDX4hmkEvCpEuGcj+qaSkH7L8JuoCHeh/fZWB7dS1Xxb+sLzQnvG8V1m/og447RGmSVBpwh3f90XreHrmf+kKCJehBVmSAS7JsTo4HjzdWODSWZ9YG3PkSxPBxBOeu8uheiqUuwMonxfz6YoKZJCCEZ96WhCMc/FDpWUQdgAgYteacWDhZy3lptrQtzZuUbeQPADkwGiQUOZAMxnNxssjjp3Yym6vkbl0We6Qqx2ymU8KvEuv74v4RuD7CNKSnvedglc9Zq/8LvvaTE0gyMcV58q/KAIMdxEt9hyRjs31UoxfKFKM=
  file:
    - _output/gotdict.mobi
    - _output/dic.html
  on:
    tags: true
    repo: wjdp/gotdict
    branch: master
env:
  global:
    secure: bqcgrvXw/ynOkS8HW5vCuGug5zFiYPyOYKyYN6F/Nndk9g9qMP9oBr0D6ssZgVL9GcKv+96p8x9bSwrCArPU1/ZUZNHPyQ3jchTfEkVrG4mifCFTC3ekDj1cKv5Et2thUs7JENSf8rmbVsxw5ckVKtmS4PHeKEh9CVYu6RnEt2aoWAbi2RUaI4YJoYwZydgR9LAqrgdP2snAC4K4eQnzINguwY7DdEi93Fi1Av+NyvPzrn/UCdk/5R8PNJcodryo+kBNzIAi8/sX1XQiMYqHlH3qetVeQw89odKFyVezcxLkejV/Et/xEqDvuB5Ghq1Vrn7LJIw1fsZZ3kt1ODWtlAITs2ZRjNmuxlxf4VD56Q3Eyr8SUKfrWHWXAqKgu3gTmKT05yPMXBBPucCHDkZtf7iNkX4SNSzOre69j2rZrJWdQhEbmnnd5Nq0OaHeNf/yFoC2KFF09re7Hu9rD/8vTS6TA3g0aAsv79EsaMzx7K+BERCIxQO+etXoC7hqtodflUNFO0iVfMLufsYquvZcV96WXChf9oUoMlzEaA2XrO7b7tMi3Nds5YFj7+Ct1iAakMRg7STqe7YAvk+8iBro3jGIW6Adyu9kbQpigLo1mDiIm/QgWlan5OO15gS7rKhMr4vIQ8ucehzS0qOadIqvSEgC95nToTAc5dz9wwjIWwY=
